// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BottomView: typeof import('./src/components/bottomView/index.vue')['default']
    ClassifySalesRanking: typeof import('./src/components/classifySalesRanking/index.vue')['default']
    CommonCard: typeof import('./src/components/commonCard/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    KeywordSearch: typeof import('./src/components/keywordSearch/index.vue')['default']
    KeywordTable: typeof import('./src/components/keywordTable/index.vue')['default']
    Map: typeof import('./src/components/map/index.vue')['default']
    MapView: typeof import('./src/components/mapView/index.vue')['default']
    Quidfill: typeof import('./src/components/quidfill/index.vue')['default']
    Quildfill: typeof import('./src/components/quildfill/index.vue')['default']
    SaleRanking: typeof import('./src/components/saleRanking/index.vue')['default']
    SalesBar: typeof import('./src/components/salesBar/index.vue')['default']
    SaleView: typeof import('./src/components/saleView/index.vue')['default']
    TodayUsers: typeof import('./src/components/todayUsers/index.vue')['default']
    TopView: typeof import('./src/components/topView/index.vue')['default']
    TotalOrders: typeof import('./src/components/totalOrders/index.vue')['default']
    TotalSales: typeof import('./src/components/totalSales/index.vue')['default']
    TotalUsers: typeof import('./src/components/totalUsers/index.vue')['default']
    Wordcloud: typeof import('./src/components/wordcloud/index.vue')['default']
  }
}
